### ISSUE TITLE
Task 5.2: Screen not locking

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#337]
Info says it's is synced, but the system is not locking.

**Comment by Anghus** [comment]
@networkingguru and @pr-honey, here's the resolution on the GDRP lab: @DouglasSteen tested the policy last night, and it worked. However, it took approximately eight hours for the policy to be applied to the VM. That's not workable in our lab environment.

So here is what I recommend. Rather than asking the student to go back and test the policy on the VM, take them to the Assignments blade and show that the policy is pending. In an Alert, explain that the policy can take up to eight hours to be applied to the VM. They can test the policy in their own environments. There is an article somewhere on Microsoft's properties that describes how long it takes for various policies to be applied. I'd recommend linking to this article as well.

**Comment by Anghus** [comment]
Once you've updated the lab, you can close this and Brian can retest. I'd recommend fixing all the existing bugs before he retests.

**Comment by pr-honey** [comment]
Done.
