### ISSUE TITLE
Task 1.9: Orphaned SIDs

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#342]
I got four orphaned SIDs in here. Not sure if this is due to the fact that we are using the same tenant across all these labs or some other issue.
![image](https://user-images.githubusercontent.com/4753203/33000511-27879a82-cd6e-11e7-8654-3268fd73626d.png)

**Comment by DouglasSteen** [comment]
I am not certain what is causing this. My *hunch* is that it is being caused by joining/in-joining the same VM from Azure/Intune/Office 365 (within the same lab). The "initial" VM does not have any of the orphaned SIDs (see attached screenshot). 


<img width="960" alt="thorncastle-issue-342-administrators properties" src="https://user-images.githubusercontent.com/31675871/33088815-99fc7f2a-cea3-11e7-8f80-084cb42ea947.png">
