### ISSUE TITLE
Task 3.5: There is no Cortana on Server

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#352]
Thank God.

**Comment by DouglasSteen** [comment]
Updated the task to use "Search" instead of "Cortana" (see following text):

"**(1) Select Knowledge, and read the note. (2) On Windows Defender Advanced Threat Protection is almost ready, under 2. Run detection test, select Copy. (3) In Internet Explorer, select Allow access; on the taskbar, in Search, type Notepad; then in the list of results, select Notepad. (4) In Microsoft Notepad, paste the script; then save the script in D:\Source$\WindowsDefenderATP as WDATP-Detection.txt. (5) Close Notepad.**"
