### ISSUE TITLE
Task 4.9 - 4.11: Suggest describing the icons

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#356]
As someone unfamiliar with this UI, I didn't know which icons were what, so stating that the 'heart' icon is Service Health would be helpful.

**Comment by DouglasSteen** [comment]
Added the following alert to Task 4.1 so that the attendee knows how to expand the list of icons and show the textual names associated with the icons:

"**On the left, you will see a list of icons. You can select the arrow at the top of the list of icons to expand the list and show the descriptive text names associated with each icon.**"
