### ISSUE TITLE
Task 1.1: Got a network prompt just after login

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#60]
If it matters, may want to tell them to click Yes or No

**Comment by timwarner-hc** [comment]
I wondered about this--Jerry, when you log into the VM, you get a prompt about network visibility. Does it matter whether we acknowledge this in the lab? I'm concerned to mention it because HOL may fix the VM in the meantime so it doesn't do it, and then the learner's going, "What am I doing wrong?!"
