### ISSUE TITLE
Task 2.1: I do not see the Cloud App Security item

### ISSUE THREAD

**Issue by networkingguru** [HoneycuttInc/Thorncastle#65]
Unable to proceed because none of the obvious ones fit the next step:
![image](https://user-images.githubusercontent.com/4753203/31523366-a44fdc8c-af78-11e7-9c10-edd4b9dc88e2.png)

**Comment by networkingguru** [comment]
Need to add a step to log out and back in to office365 to fix this.

**Comment by timwarner-hc** [comment]
Not necessary because the access codes the learner receives in lab HOL-SC1-1A provide them access to the proper Office 365 subscription level, and Cloud App Security appears on the admin menu as expected.

However, I did remove the instructions for signing up for a trial as they are no longer needed.
